### ISSUE TITLE
Clippy warnings in library code

### ISSUE THREAD

**Issue by geigerzaehler** [daniel5151/gdbstub#114]
When I run `cargo clippy --lib` in the existing code base I see a couple of warnings although the pull request template asks me to check that there are no clippy warnings. It looks like CI does not run clippy for the library target.

**Comment by daniel5151** [comment]
Could you post a screenshot / test output of what warnings you're seeing? I just ran `cargo clippy` locally and I'm not seeing what you're talking about.

**Comment by daniel5151** [comment]
Hmm, weird...

My Github Actions-fu isn't all that great. If you'd like to take a stab at pushing up a CI fix PR, I'd be happy to merge it in. Otherwise, I'll close this for now :)
