### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by sapir** [daniel5151/gdbstub#3]

**Comment by daniel5151** [comment]
Thanks for the interest!

While there's still quite a bit of cleanup / refactoring I'd like to do to `gdbstub` (including a large refactor that removes the dependency on `alloc` entirely), I certainty don't mind publishing "gdbstub 0.1" to crates.io.

The only real blocker to publishing the crate is missing docs and examples.  Thanks to COVID-19, I've suddenly got lots of free time on my hands, so I should be able to do a documentation pass in the next couple weeks.

**Comment by sapir** [comment]
Thanks for making this!

fwiw there are "examples" at:
* https://github.com/michelhe/rustboyadvance-ng
* https://github.com/sapir/microcorruption-emu

**Comment by daniel5151** [comment]
https://crates.io/crates/gdbstub
