### ISSUE TITLE
`output!` macro in console_output.rs uses `writeln!` instead of intended `write!`

### ISSUE THREAD

**Issue by DrChat** [daniel5151/gdbstub#41]
https://github.com/daniel5151/gdbstub/blob/bfe9a7b92ef86f2638c7207fb7d561e30432f85f/src/protocol/console_output.rs#L74-L80

This causes newlines to be printed to the GDB console when using the `output!` macro.

**Comment by daniel5151** [comment]
Good catch!

I'll try to find some time this weekend to publish `gdbstub 0.4.4` that fixes this issue.

Thanks for reporting it!

**Comment by DrChat** [comment]
Sounds good - appreciate it!

**Comment by daniel5151** [comment]
The fix is in, and included in the just-published `gdbstub 0.4.4`!

**Comment by DrChat** [comment]
Appreciate the quick turnaround!

**Comment by daniel5151** [comment]
Yeah, no problem! 
It's not like the project is active and popular enough to require rolling releases, so I may as well push out fixes as they come in 😄 

* * *

By the way, if you get the chance, let me know what you thought about `gdbstub` by dropping a comment on #31! I know the library's structure is a bit... unorthadox compared to other Rust libraries, so any and all feedback about the API would be much appreciated!
