### ISSUE TITLE
gdbstub_arch package doesn't contain LICENSE file

### ISSUE THREAD

**Issue by keiichiw** [daniel5151/gdbstub#67]
`gdbstub_arch-0.1.0` package distributed on [crates.io](https://crates.io/crates/gdbstub_arch) doesn't contain LICENSE file while its Cargo.toml says its license is MIT.

```bash
$ curl -L 'https://crates.io/api/v1/crates/gdbstub_arch/0.1.0/download' > /tmp/gdbstub_arch-0.1.0.tar.gz
$ tar xvf /tmp/gdbstub_arch-0.1.0.tar.gz
$ cat gdbstub_arch-0.1.0/LICENSE
cat: gdbstub_arch-0.1.0/LICENSE: No such file or directory
```

@daniel5151 Could you release the updated version (0.1.1?) with LICENSE included?

**Comment by daniel5151** [comment]
Ah, good catch! Sorry about that!

I'll publish a new version sometime today / tomorrow.

**Comment by daniel5151** [comment]
`gdbstub_arch` 0.1.1 is now published, and includes a LICENSE file 🎉

**Comment by keiichiw** [comment]
Thank you for the quick update!

**Comment by daniel5151** [comment]
No problem 😄 
And thank you for the support!
