### ISSUE TITLE
RIP size on x86-64

### ISSUE THREAD

**Issue by gz** [daniel5151/gdbstub#80]
[rip size](https://github.com/daniel5151/gdbstub/blob/52ae3c7cf2cb7298925a1ba5b4ed1e904ae64416/gdbstub_arch/src/x86/reg/id.rs#L175) is currently 4 bytes, but maybe it should be 8?

https://github.com/bminor/binutils-gdb/blob/master/gdb/features/i386/64bit-core.xml lists it as:

```xml
  <reg name="rip" bitsize="64" type="code_ptr"/>
```

**Comment by bet4it** [comment]
I will fix it in a following PR ( with another way ) , wait for me😅

**Comment by gz** [comment]
random thought: it might be nice to statically type-encode the size of the registers when when they're passed to the read/write_registers. One way could be to move the `val: &[u8]` and `dst: &mut [u8]` in some enum with the RegId and encode the length explicitly (specify as &[u8; 8] etc.)?

I'm thinking that might save some slice length checks when implementing these functions. But not sure if even possible just a thought :)

**Comment by daniel5151** [comment]
@gz I assume you meant `read/write_register` (as opposed to `read/write_registers`)?

If so, then you might find this discussion from the initial implementation PR interesting: https://github.com/daniel5151/gdbstub/pull/22#issuecomment-683889998

Though now that I'm re-reading this idea a year later, I realize that there might be some easier approaches to pull off something similar... I certainly wouldn't be opposed to having stricter type-safety in these APIs, so I'm open to any ideas!

**Comment by daniel5151** [comment]
And as for the original issue: yes, this seems like an oversight in the initial #34 implementation. 

Pinging @keiichiw, since this might translate to a subtle correctness issue in your implementation.

**Comment by gz** [comment]
Yes I meant the single register writes with the dynamic `val` and `dst` slices.

**Comment by daniel5151** [comment]
@gz if this is something you'd like fixed sooner, feel free to send a quick fixup PR. Otherwise, a fix for this will land alongside some other changes to `read_register` in #85

**Comment by gz** [comment]
Sent pull request, yes would be nice to have this fixed, thanks!
